/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FMcreationcompte (void);
GtkWidget* create_FMcrudcommandes (void);
GtkWidget* create_Fmcrud (void);
GtkWidget* create_FMmodif (void);
GtkWidget* create_BMwindowcapt (void);
GtkWidget* create_BMwindowmodifier (void);
GtkWidget* create_gestioncommande (void);
GtkWidget* create_RKcrud (void);
GtkWidget* create_RKajout (void);
GtkWidget* create_Rkmodifier (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_FMconnexion (void);
GtkWidget* create_Admin (void);
GtkWidget* create_MHwindowrec (void);
GtkWidget* create_MHwindownaissance (void);
GtkWidget* create_MHwindowmodif (void);
GtkWidget* create_MHwindowAffichage (void);
GtkWidget* create_MBcrud (void);
GtkWidget* create_MBajout (void);
GtkWidget* create_MBmodif (void);
GtkWidget* create_MBwarn (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_dialog6 (void);
GtkWidget* create_dialog7 (void);
GtkWidget* create_dialog8 (void);
GtkWidget* create_dialog9 (void);
GtkWidget* create_dialog10 (void);
GtkWidget* create_dialog11 (void);
GtkWidget* create_MABFcrud (void);
GtkWidget* create_dashbord (void);
