/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FMcreationcompte (void);
GtkWidget* create_FMcrudcommandes (void);
GtkWidget* create_Fmcrud (void);
GtkWidget* create_FMmodif (void);
GtkWidget* create_BMwindowcapt (void);
GtkWidget* create_BMwindowmodifier (void);
GtkWidget* create_colorselectiondialog1 (void);
GtkWidget* create_Admin (void);
GtkWidget* create_FMconnexion (void);
GtkWidget* create_gestioncommande (void);
GtkWidget* create_RKcrud (void);
GtkWidget* create_RKajout (void);
GtkWidget* create_Rkmodifier (void);
