/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

void gtk_label_set_markup(GtkLabel *label, const gchar *str);
int
main (int argc, char *argv[])
{

  GtkWidget *FMconnexion;
  GtkWidget *FMcreationcompte;
  GtkWidget *FMcrudcommandes;
   GtkWidget *Fmcrud;
  GtkWidget *FMmodif;
GtkWidget *BMwindowcapt;
  GtkWidget *BMwindowmodifier;
  GtkWidget *colorselectiondialog1;
GtkWidget *Admin;
GtkWidget *gestioncommande;
GtkWidget *RKcrud;
GtkWidget *RKajout;
GtkWidget *RKmodifier;
GtkWidget *MBajout;
GtkWidget *MBcrud;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
/*Admin = create_Admin ();
  gtk_widget_show (Admin);*/
 
/* colorselectiondialog1 = create_colorselectiondialog1 ();
  gtk_widget_show (colorselectiondialog1);*/
GdkColor color;

  /*color.red=0xFF9966;
  color.green=0xFF9966;
  color.blue=0xFF9966F;*/
//gdk_color_parse ("0xFFF2ED", &color);
gdk_color_parse ("green", &color);
gtk_widget_modify_bg(GTK_WIDGET(Admin),GTK_STATE_NORMAL,&color);

 /*BMwindowcapt = create_BMwindowcapt ();
  gtk_widget_show (BMwindowcapt);
 BMwindowmodifier = create_BMwindowmodifier ();
  gtk_widget_show (BMwindowmodifier);*/
/*
gestioncommande = create_gestioncommande ();
  gtk_widget_show (gestioncommande);
*/


/*
MBcrud = create_MBcrud ();
  gtk_widget_show (MBcrud);
MBajout = create_MBajout ();
  gtk_widget_show (MBajout);*/


  FMconnexion = create_FMconnexion ();
  gtk_widget_show (FMconnexion);

  /*FMcreationcompte = create_FMcreationcompte ();
  gtk_widget_show (FMcreationcompte);
Fmcrud = create_Fmcrud ();
  gtk_widget_show (Fmcrud);*/

  /*FMcrudcommandes = create_FMcrudcommandes ();
  gtk_widget_show (FMcrudcommandes);*/
/*gdk_color_parse ("red", &color1);
gtk_widget_modify_bg(GTK_WIDGET(FMcrudcommandes),GTK_STATE_NORMAL,&color);*/
/*FMmodif = create_FMmodif ();
  gtk_widget_show (FMmodif);*/

/*RKcrud = create_RKcrud ();
  gtk_widget_show (RKcrud);*/
/*RKajout = create_RKajout ();
  gtk_widget_show (RKajout);*/
/*RKmodifier = create_RKmodifier ();
  gtk_widget_show (RKmodifier);*/


  gtk_main ();
  return 0;
}

